const products = [
  {
    name: "Guess MINTHA",
    slug: "guess-mintha",
    price: 120,
    category: "bags",
    image: "/images/Guess MINTHA.jpg",
    discount: 30, 
    availability: 42,
    description: `Small handbag from Guess collection. Closed model made of faux leather.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess MINTHA.jpg", "/images/Guess MINTHA a.jpg"],
  },
  {
    name: "Guess DAVIKA",
    slug: "guess-davika",
    price: 95,
    category: "bags",
    image: "/images/Guess DAVIKA.jpg",
    discount: 10, 
    availability: 17,
    description: `Medium handbag from Guess collection. Closed model is made of imitation suede.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess DAVIKA.jpg", "/images/Guess DAVIKA a.jpg"],
  },
  {
    name: "Guess MALVA",
    slug: "guess-malva",
    price: 75,
    category: "bags",
    image: "/images/Guess MALVA.jpg",
    discount: 0,
    availability: 63,
    description: `Medium handbag from Guess collection. Closed model is made of suede.`,
    materials: ["Main material: 100% Suede", "Lining: 80% Polyester, 20% Cotton", "Trim: 100% Polyurethane"],
    additionalImages: ["/images/Guess MALVA.jpg", "/images/Guess MALVA a.jpg"],
  },
  {
    name: "Guess NOLANA",
    slug: "guess-nolana",
    price: 98,
    category: "bags",
    image: "/images/Guess NOLANA.jpg",
    availability: 29,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["Main material: 100% PU", "Outsole: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess NOLANA.jpg", "/images/Guess NOLANA a.jpg"],
  },
  {
    name: "Guess SORA",
    slug: "guess-sora",
    price: 130,
    category: "bags",
    image: "/images/Guess SORA.jpg",
    availability: 54,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: ["/images/Guess SORA.jpg", "/images/Guess SORA a.jpg"],
  },
  {
    name: "Guess SELA",
    slug: "guess-sela",
    price: 90,
    category: "bags",
    image: "/images/Guess SELA.jpg",
    availability: 38,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess SELA.jpg", "/images/Guess SELA a.jpg"],
  },
  {
    name: "Guess DAVIKA2",
    slug: "guess-davika2",
    price: 95,
    category: "bags",
    image: "/images/Guess DAVIKA2.jpg",
    availability: 76,
    description: `Medium handbag from Guess collection. Closed model is made of imitation suede.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess DAVIKA2.jpg", "/images/Guess DAVIKA2 a.jpg"],
  },
  {
    name: "Calvin Klein Jeans",
    slug: "calvin-klein-jeans",
    price: 150,
    category: "bags",
    image: "/images/Calvin Klein Jeans.jpg",
    availability: 51,
    description: `Small handbag from Calvin Klein Jeans. Closing model is made of faux leather.`,
    materials: ["100% Polyester"],
    additionalImages: ["/images/Calvin Klein Jeans.jpg", "/images/Calvin Klein Jeans a.jpg"],
  },
  {
    name: "U.S. Polo Assn. Jones",
    slug: "us-polo-assn-jones",
    price: 110,
    category: "bags",
    image: "/images/U.S. Polo Assn. Jones.jpg",
    availability: 22,
    description: `Small handbag from U.S. Polo Assn collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: ["/images/U.S. Polo Assn. Jones.jpg", "/images/U.S. Polo Assn. Jones a.jpg"],
  },
  {
    name: "U.S. Polo Assn. Sunshine",
    slug: "us-polo-assn-sunshine",
    price: 105,
    category: "bags",
    image: "/images/U.S. Polo Assn. Sunshine.jpg",
    availability: 89,
    description: `Large handbag from U.S. Polo Assn collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: ["/images/U.S. Polo Assn. Sunshine.jpg", "/images/U.S. Polo Assn. Sunshine a.jpg"],
  },
  {
    name: "Karl Lagerfeld",
    slug: "karl-lagerfeld",
    price: 160,
    category: "bags",
    image: "/images/Karl Lagerfeld.jpg",
    availability: 34,
    description: `Small handbag from the Karl Lagerfeld collection. Closed model is made of a combination of textile fabric and faux leather.`,
    materials: ["Base material: 60% Recycled polyamide, 40% Polyurethane", "Lining: 100% Recycled polyester"],
    additionalImages: ["/images/Karl Lagerfeld.jpg", "/images/Karl Lagerfeld a.jpg"],
  },
  {
    name: "Juicy Couture Blossom",
    slug: "juicy-couture-blossom",
    price: 85,
    category: "bags",
    image: "/images/Juicy Couture Blossom.jpg",
    availability: 67,
    description: `Small handbag from Juicy Couture collection. Closed model is made of velour material.`,
    materials: ["100% Polyester"],
    additionalImages: ["/images/Juicy Couture Blossom.jpg", "/images/Juicy Couture Blossom a.jpg"],
  },
  {
    name: "Juicy Couture Jasmine",
    slug: "juicy-couture-jasmine",
    price: 105,
    category: "bags",
    image: "/images/Juicy Couture Jasmine.jpg",
    availability: 49,
    description: `Medium handbag from Juicy Couture collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: ["/images/Juicy Couture Jasmine.jpg", "/images/Juicy Couture Jasmine a.jpg"],
  },
];

export default products;
