// utils/productsData.js
const products = [
  {
    name: "Guess MINTHA",
    slug: "guess-mintha",
    price: 120,
    category: "bags",
    image: "/images/Guess MINTHA.jpg",
    discount: 30,
    availability: 42,
    available: true,
    description: `Small handbag from Guess collection. Closed model made of faux leather.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: [
      "/images/Guess MINTHA.jpg",
      "/images/Guess MINTHA a.jpg",
    ],
  },
  {
    name: "Guess DAVIKA",
    slug: "guess-davika",
    price: 95,
    category: "bags",
    image: "/images/Guess DAVIKA.jpg",
    discount: 10,
    availability: 17,
    available: true,
    description: `Medium handbag from Guess collection. Closed model is made of imitation suede.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: [
      "/images/Guess DAVIKA.jpg",
      "/images/Guess DAVIKA a.jpg",
    ],
  },
  {
    name: "Guess MALVA",
    slug: "guess-malva",
    price: 75,
    category: "bags",
    image: "/images/Guess MALVA.jpg",
    discount: 0,
    availability: 63,
    available: true,
    description: `Medium handbag from Guess collection. Closed model is made of suede.`,
    materials: [
      "Main material: 100% Suede",
      "Lining: 80% Polyester, 20% Cotton",
      "Trim: 100% Polyurethane",
    ],
    additionalImages: [
      "/images/Guess MALVA.jpg",
      "/images/Guess MALVA a.jpg",
    ],
  },
  {
    name: "Guess NOLANA",
    slug: "guess-nolana",
    price: 98,
    category: "bags",
    image: "/images/Guess NOLANA.jpg",
    discount: 0,
    availability: 0, // Недоступен
    available: false,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["Main material: 100% PU", "Outsole: 80% Polyester, 20% Cotton"],
    additionalImages: [
      "/images/Guess NOLANA.jpg",
      "/images/Guess NOLANA a.jpg",
    ],
  },
  {
    name: "Guess SORA",
    slug: "guess-sora",
    price: 130,
    category: "bags",
    image: "/images/Guess SORA.jpg",
    discount: 0,
    availability: 54,
    available: true,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: ["/images/Guess SORA.jpg", "/images/Guess SORA a.jpg"],
  },
  {
    name: "Guess SELA",
    slug: "guess-sela",
    price: 90,
    category: "bags",
    image: "/images/Guess SELA.jpg",
    discount: 0,
    availability: 0, // Недоступен
    available: false,
    description: `Medium handbag from Guess collection. Closing model is made of faux leather.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: ["/images/Guess SELA.jpg", "/images/Guess SELA a.jpg"],
  },
  {
    name: "Guess DAVIKA2",
    slug: "guess-davika2",
    price: 95,
    category: "bags",
    image: "/images/Guess DAVIKA2.jpg",
    discount: 0,
    availability: 76,
    available: true,
    description: `Medium handbag from Guess collection. Closed model is made of imitation suede.`,
    materials: ["Main material: 100% PU", "Lining: 80% Polyester, 20% Cotton"],
    additionalImages: [
      "/images/Guess DAVIKA2.jpg",
      "/images/Guess DAVIKA2 a.jpg",
    ],
  },
  {
    name: "Calvin Klein Jeans",
    slug: "calvin-klein-jeans",
    price: 150,
    category: "bags",
    image: "/images/Calvin Klein Jeans.jpg",
    discount: 0,
    availability: 51,
    available: true,
    description: `Small handbag from Calvin Klein Jeans. Closing model is made of faux leather.`,
    materials: ["100% Polyester"],
    additionalImages: [
      "/images/Calvin Klein Jeans.jpg",
      "/images/Calvin Klein Jeans a.jpg",
    ],
  },
  {
    name: "U.S. Polo Assn. Jones",
    slug: "us-polo-assn-jones",
    price: 110,
    category: "bags",
    image: "/images/U.S. Polo Assn. Jones.jpg",
    discount: 0,
    availability: 22,
    available: true,
    description: `Small handbag from U.S. Polo Assn collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: [
      "/images/U.S. Polo Assn. Jones.jpg",
      "/images/U.S. Polo Assn. Jones a.jpg",
    ],
  },
  {
    name: "U.S. Polo Assn. Sunshine",
    slug: "us-polo-assn-sunshine",
    price: 105,
    category: "bags",
    image: "/images/U.S. Polo Assn. Sunshine.jpg",
    discount: 0,
    availability: 89,
    available: true,
    description: `Large handbag from U.S. Polo Assn collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: [
      "/images/U.S. Polo Assn. Sunshine.jpg",
      "/images/U.S. Polo Assn. Sunshine a.jpg",
    ],
  },
  {
    name: "Karl Lagerfeld",
    slug: "karl-lagerfeld",
    price: 160,
    category: "bags",
    image: "/images/Karl Lagerfeld.jpg",
    discount: 0,
    availability: 34,
    available: true,
    description: `Small handbag from the Karl Lagerfeld collection. Closed model is made of a combination of textile fabric and faux leather.`,
    materials: [
      "Base material: 60% Recycled polyamide, 40% Polyurethane",
      "Lining: 100% Recycled polyester",
    ],
    additionalImages: [
      "/images/Karl Lagerfeld.jpg",
      "/images/Karl Lagerfeld a.jpg",
    ],
  },
  {
    name: "Juicy Couture Blossom",
    slug: "juicy-couture-blossom",
    price: 85,
    category: "bags",
    image: "/images/Juicy Couture Blossom.jpg",
    discount: 0,
    availability: 67,
    available: true,
    description: `Small handbag from Juicy Couture collection. Closed model is made of velour material.`,
    materials: ["100% Polyester"],
    additionalImages: [
      "/images/Juicy Couture Blossom.jpg",
      "/images/Juicy Couture Blossom a.jpg",
    ],
  },
  {
    name: "Juicy Couture Jasmine",
    slug: "juicy-couture-jasmine",
    price: 105,
    category: "bags",
    image: "/images/Juicy Couture Jasmine.jpg",
    discount: 0,
    availability: 49,
    available: true,
    description: `Medium handbag from Juicy Couture collection. Closing model is made of faux leather.`,
    materials: ["100% Polyurethane"],
    additionalImages: [
      "/images/Juicy Couture Jasmine.jpg",
      "/images/Juicy Couture Jasmine a.jpg",
    ],
  },
  // Футболки
  {
    name: "Basic T-Shirt",
    slug: "basic-t-shirt",
    price: 25,
    category: "tshirt",
    image: "/images/T-Shirt1.jpeg",
    discount: 0,
    availability: 100,
    available: true,
    description: `Comfortable basic T-Shirt, perfect for casual wear.`,
    materials: ["100% Cotton"],
    additionalImages: ["/images/T-Shirt1.jpeg", "/images/T-Shirt2.jpeg"],
  },
  // Свитера
  {
    name: "Classic Sweater",
    slug: "classic-sweater",
    price: 50,
    category: "sweaters",
    image: "/images/Sweater2.jpeg",
    discount: 0,
    availability: 60,
    available: true,
    description: `Warm and cozy sweater for colder days.`,
    materials: ["80% Wool, 20% Acrylic"],
    additionalImages: ["/images/Sweater2.jpeg", "/images/Sweater1.jpeg"],
  },
  {
    name: "Slim Fit Jeans",
    slug: "slim-fit-jeans",
    price: 45,
    category: "pants",
    image: "/images/Pants1.jpeg",
    discount: 0,
    availability: 70,
    available: true,
    description: `Classic slim-fit jeans made of high-quality denim.`,
    materials: ["99% Cotton, 1% Elastane"],
    additionalImages: ["/images/Pants1.jpeg", "/images/Pants2.jpeg"],
  },
  {
    name: "Leather Wallet",
    slug: "leather-wallet",
    price: 45,
    category: "extra",
    image: "/images/Earingss1.jpeg",
    discount: 0,
    availability: 120,
    available: true,
    description: `High-quality leather wallet with multiple compartments.`,
    materials: ["100% Leather"],
    additionalImages: ["/images/Earingss1.jpeg"],
  },
];

export default products;
