import { Afacad } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"

const afacad = Afacad({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={afacad.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
